services:
  db:
    image: postgres:16.3
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vacuum_experiment_development
    ports:
      - '5442:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local